{% set name = "gsw-xarray" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gsw-xarray-{{ version }}.tar.gz
  sha256: f89c27a9f37549a1a6ed88a002201b880a8ae2463e711e74030e43101a62e185

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - gsw >=3.4.0
    - python >=3.8
    - xarray >=0.20.2

test:
  imports:
    - gsw_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DocOtak/gsw-xarray
  summary: Drop in wrapper for gsw which adds CF standard name and units attributes to xarray results
  license: BSD-3-Clause
  license_file: LICENSE.rst
  dev_url: https://gsw-xarray.readthedocs.io/

extra:
  recipe-maintainers:
    - rcaneill
    - DocOtak
