{% set name = "gsw-xarray" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa389b0e237f9ce9b64bfe3e3c16a0367c750d0b54185d3c4817dd89951721ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - gsw >=3.4.0
    - python >={{ python_min }}
    - xarray >=0.20.2
    - cf_xarray <0.8.0,>=0.7.4
  run_constrained:
    - pint-xarray <0.4,>=0.3
    - Pint >=0.20

test:
  imports:
    - gsw_xarray
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DocOtak/gsw-xarray
  summary: Drop in wrapper for gsw which adds CF standard name and units attributes to xarray results
  license: BSD-3-Clause
  license_file: LICENSE.rst
  dev_url: https://gsw-xarray.readthedocs.io/

extra:
  recipe-maintainers:
    - rcaneill
    - DocOtak
